
services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: AShelter
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
    container_name: golang_app
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: AShelter
      DB_HOST: db
      DB_PORT: 5432
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: animal-shelter-media
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    entrypoint: [ "./wait-for-it.sh", "minio:9000", "--", "/app/main" ]
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER: "on"
      MINIO_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "9000:9000" # API MinIO
      - "9001:9001" # Web UI MinIO
    volumes:
      - minio_data:/data
    networks:
      - app_network

volumes:
  db_data:
  minio_data:

networks:
  app_network:
